package g1.detran.igu;

public enum OpcaoMenu {
	ITEMMEMORIA,
	ITEMARQUIVO,
	CONDUTORMANUAL,	
	VEICULOMANUAL,
	INFRACAOMANUAL,
	ITEMVEICULOAUTOMATICO,
	ITEMCONDUTORAUTOMATICO,
	INFRACAOAUTOMATICO,	
	SOBRE,
	SAIR,
	MOSTRAR,
	INFRACOESCPF,
	INFRACAOVEICULO,
	MAIORESINFRATORES,
	INFRACAOPORPERIODO

}
